### Send POST request with json body
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "luiz@noreply.com",
  "password": "changeme"
}

> {% client.global.set("access_token", response.body.access_token); %}


### GET request with a header
GET http://localhost:3000
Accept: application/json
Authorization: Bearer {{access_token}}


### Send POST request with json body
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Luiz Henrique",
  "document": "83110730073",
  "emailNotification": true,
  "smsNotification": true,
  "type": "company",
  "email": "luiz@noreply.com",
  "password": "changeme"
}

### POST ADD CREDIT
POST http://localhost:3000/wallets
Content-Type: application/json

{
  "id": 3,
  "amount": 10.40
}

### POST TRANSACTION
POST http://localhost:3000/transactions
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "transactionToId": 1,
  "transactionFromId": 2,
  "amount": 10.0
}