### POST to login and set the auth token
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "luiz@noreply.com",
  "password": "changeme"
}

> {% client.global.set("access_token", response.body.access_token); %}

### POST to create a new company user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Luiz Henrique",
  "document": "75072195000184",
  "emailNotification": true,
  "smsNotification": true,
  "type": "company",
  "email": "luiz@noreply.com",
  "password": "changeme"
}

### POST to create a new common user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Fernando Pascoal",
  "document": "95344973047",
  "emailNotification": true,
  "smsNotification": true,
  "type": "person",
  "email": "fernando@noreply.com",
  "password": "changeme"
}

### POST to add credits to an account
POST http://localhost:3000/wallets
Content-Type: application/json

{
  "id": 3,
  "amount": 10.40
}

### POST TRANSACTION
POST http://localhost:3000/transactions
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "transactionToId": 1,
  "transactionFromId": 2,
  "amount": 10.0
}